runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

#[START gae_flex_postgres_env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://test-user:test@/userclass?host=/cloudsql/test-sdhacks:us-central1:help-me
#[END gae_flex_postgres_env]

#[START gae_flex_postgres_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: test-sdhacks:us-central1:help-me
#[END gae_flex_postgres_settings]
